### ISSUE TITLE
pls include example of ignoring directory

### ISSUE THREAD

**Issue by the1mills** [es128/anymatch#14]
Classic use case is to ignore any contents of any node_modules directory, where they may be many of these directories in a project.

For use with chokidar, I simply cannot say whether this:

```
const opts ={
  ignored: ['node_modules']
}
```

will ignore just the top-level node_modules dir, or any node_modules dir?
can this be documented with anymatch?

thank you!

**Comment by es128** [comment]
Well, anymatch's behavior is to just do a straight string match on a non-glob string like that. Chokidar, in order to account for the possibility that the string may be a directory name, will automatically add an entry to that array for `node_modules/**` to ignore all children of an ignored directory.

So, I suppose this point needs to be documented better within Chokidar. Maybe a note can be added here too, but I'm not sure what it should say. I'm open to suggestions.

**Comment by jonschlinkert** [comment]
the convention for matching directories like this would be `**/node_modules/**`. This is the recommended way in minimatch, glob, micromatch, etc

**Comment by the1mills** [comment]
yes please add somewhere in the docs that to ignore contents of a dir that
it needs to be

**/some-dir/**

otherwise you leave ppl guessing

**Comment by the1mills** [comment]
yes please add somewhere in the docs that to ignore contents of a dir that
it needs to be

**/some-dir/**

otherwise you leave ppl guessing
On Oct 10, 2016 12:13 PM, "Jon Schlinkert" <notifications@github.com> wrote:

the convention for matching directories like this would be
**/node_modules/**. This is the recommended way in minimatch, glob,
micromatch, etc

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/es128/anymatch/issues/14#issuecomment-252718528>, or mute
the thread

**Comment by jonschlinkert** [comment]
A pr is welcome, otherwise we can add that to the readme the next time it's edited

**Comment by es128** [comment]
A regex approach would also be possible... I guess I'm still struggling to see where making this points fits in the docs (and is it anymatch or chokidar docs?)

Maybe adding an examples section or user guide (as opposed to what would currently be better described as an integrators' guide) to the readme here would be good. There was also a Brunch user that complained that linking to the anymatch readme was not sufficiently clear about how to use it in their config, so I'd want to try to cover that concern as well if we're trying to brush up docs.

**Comment by jonschlinkert** [comment]
> I guess I'm still struggling to see where making this points fits in the docs (and is it anymatch or chokidar docs?)

I agree, I almost said "this is a globbing specification thing" but it's not really. It's probably good to mention on both readmes (here and chokidar), especially if the libraries are modifying the paths from what the user actually entered. 

In other words, if I enter `node_modules/**`, is that being modified to something like `path.join(cwd, 'node_modules/**')`? If so, this is why the user needs to do `**/node_modules/**`

**Comment by jonschlinkert** [comment]
Maybe we should come up with a brief, one-paragraph preamble that we can use at the top of related libs. Something like:

"Glob patterns are similar to regular expressions, there are some rules that need to be followed for effective matching:..." etc

I can work on a cheatsheet too if you think that's a good idea. We can then link to that as well.

**Comment by es128** [comment]
> In other words, if I enter node_modules/**, is that being modified to something like path.join(cwd, 'node_modules/**')? If so, this is why the user needs to do **/node_modules/**

It's a little hard to describe simply because of the various ways different options play into it, but the intention is to operate on the principle of least surprise. A string is treated as a path, so providing `'node_modules'` means match/ignore the top-level entry with that name and all its children if it's a dir (accomplished internally by appending `/**`). If the `cwd` option is specified by the user then it does get joined with that, but not if it isn't (i.e. all the paths will be treated as relative within chokidar). If you want to exclude any subdir anywhere with that name, then yes `'**/node_modules/**'` is a good way to do it, but `/node_modules/` would also work (with the nuance that it would also match/ignore dirs named things like `node_modules_bak`).

The whole goal of this lib is to give users the flexibility to use whichever paradigm they're comfortable with and works best for the situation. But I get that flexibility can be its own type of complexity (timtowtdi).

**Comment by es128** [comment]
Yeah a general primer on globbing would be good, but anymatch also provides a few other ways of matching paths, and that seems it ought to be conveyed better than it is now.

**Comment by jonschlinkert** [comment]
closed by https://github.com/es128/anymatch/pull/15
